/** @typedef {{
 *   id: string,
 *   name: string,
 *   region: string,
 *   dept: string,
 *   position: string,
 *   phone: string,
 *   email?: string,
 *   address?: string,
 *   avatar?: string
 * }} Contact */

/** @type {Contact[]} */
const CONTACTS = [
  {
    id: "1",
    name: "김민수",
    region: "서울",
    dept: "본부",
    position: "회장",
    phone: "010-1234-5678",
    email: "minsu.kim@example.com",
    address: "서울특별시 중구 세종대로 110",
  },
  {
    id: "2",
    name: "이서연",
    region: "서울",
    dept: "사무국",
    position: "사무국장",
    phone: "010-2345-6789",
    email: "seoyeon.lee@example.com",
    address: "서울특별시 종로구 종로 1",
  },
  {
    id: "3",
    name: "박준호",
    region: "경기",
    dept: "경기도회",
    position: "회장",
    phone: "010-3456-7890",
    email: "junho.park@example.com",
    address: "경기도 수원시 영통구 광교로 209",
  },
  {
    id: "4",
    name: "최유진",
    region: "경기",
    dept: "경기도회",
    position: "부회장",
    phone: "010-4567-8901",
    email: "yujin.choi@example.com",
  },
  {
    id: "5",
    name: "정인규",
    region: "경남",
    dept: "경남도회",
    position: "회장",
    phone: "010-4566-3080",
    email: "ingyu.jung@example.com",
    address: "경상남도 창원시 의창구 중앙대로 151",
  },
  {
    id: "6",
    name: "한동욱",
    region: "경남",
    dept: "경남도회",
    position: "육군부회장",
    phone: "010-3215-9949",
    email: "dongwook.han@example.com",
  },
  {
    id: "7",
    name: "오하늘",
    region: "부산",
    dept: "부산시회",
    position: "회장",
    phone: "010-5678-9012",
    email: "haneul.oh@example.com",
    address: "부산광역시 연제구 중앙대로 1001",
  },
  {
    id: "8",
    name: "윤재석",
    region: "부산",
    dept: "부산시회",
    position: "총무",
    phone: "010-6789-0123",
    email: "jaeseok.yoon@example.com",
  },
  {
    id: "9",
    name: "강미라",
    region: "대전",
    dept: "사무국",
    position: "과장",
    phone: "010-7890-1234",
    email: "mira.kang@example.com",
    address: "대전광역시 서구 둔산로 100",
  },
  {
    id: "10",
    name: "조현우",
    region: "대구",
    dept: "대구시회",
    position: "부회장",
    phone: "010-8901-2345",
    email: "hyunwoo.cho@example.com",
  },
  {
    id: "11",
    name: "신예린",
    region: "인천",
    dept: "인천시회",
    position: "총무",
    phone: "010-9012-3456",
    email: "yerin.shin@example.com",
    address: "인천광역시 남동구 예술로 178",
  },
  {
    id: "12",
    name: "임성호",
    region: "광주",
    dept: "광주시회",
    position: "회장",
    phone: "010-0123-4567",
    email: "seongho.lim@example.com",
  }
];
